### ISSUE TITLE
Scripting request POST issue

### ISSUE THREAD

**Issue by luizzenha** [TestMace/TestMace-issues#28]
I'm trying to create a script that will post and the returned values will be stored in dynamic variables.
But at run the script, the RUN button stuck at grey and locked.

It does not matter what post url.

I'm running at 0.0.1-beta.25

![image](https://user-images.githubusercontent.com/20114208/69886392-7f7ada80-12c0-11ea-9fc5-a0fe206ca54e.png)

**Comment by dima11221122** [comment]
Hi, @luizzenha. We've reproduced the issue. I think we'll fix it in the next release.

**Comment by luizzenha** [comment]
Thanks!

**Comment by Ratuvog** [comment]
We have fixed this bug in the latest release. Unfortunately, we still cannot handle all the possible cases of the chain of asynchronous calls in order to unambiguously understand that the script should end. We did the following things:
-   We set a 30 second timeout for script execution after which the script will end with an error.
-   Added the ability to call the `finish()` function in the program interface which reports the early completion of the script.

Actually, we added this information to our documentation. https://docs.testmace.com/node-types/script#assinkhronnyi-kod
